### ISSUE TITLE
token service: AT  does not contain endpoint scopes

### ISSUE THREAD

**Issue by AdhilJ** [networknt/light-oauth2#111]
Hi,

I  downloaded **light-oauth2 PostGres** implementaion in my local.
I tested the OAuth flow and noticed the token service not returning "Service endpoint scopes" in Access Token.

I see the endpoint scopes returned (in new_scope) during  ‘**Link service endpoint to client**’ step.  
However, I am not getting this new scope info in AccessToken. 

**_Register client:_**
curl -k -H "Content-Type: application/json" -X POST -d '{"clientType":"trusted","clientProfile":"mobile","clientName":"MyApp","clientDesc":"Mobile Online  Application","scope":"t.r t.w","redirectUri": "http://m.localhost:8080/test","ownerId":"admin"}' https://localhost:6884/oauth2/client

**_Register service & Endpoint:_**
curl -k -H "Content-Type: application/json" -X POST -d '{"serviceId":"mysvc-0002","serviceType":"swagger","serviceName":"api-weather-service","serviceDesc":"Microservices get weather details","scope":"","ownerId":"admin"}' https://localhost:6883/oauth2/service
curl -k -H "Content-Type: application/json" -X POST -d '[{"endpoint":"/v2/gethourlyweather@get","operation":"getHourly","scope":"data.r"}]' https://localhost:6883/oauth2/service/mysvc-0002/endpoint

**_Link service endpoints to a client._**
curl -k -H "Content-Type: application/json" -X POST -d '["/v2/gethourlyweather@get"]' https://localhost:6884/oauth2/client/7a3f5f5c-61c8-4b67-8e6d-d95e717dc07d/service/mysvc-0002
Response:
{"old_scope":"t.r t.w",**"new_scope":"data.r"**}

**_Get Access Token:_**
curl -k -H "Authorization: Basic 7a3f5f5c-61c8-4b67-8e6d-d95e717dc07d:07cmL9lTTe-Et9aP8Rwv9Q" -H "Content-Type: application/x-www-form-urlencoded" -X POST -d "grant_type= client_credentials &userId=admin&userType=Employee&transit=12345" https://localhost:6882/oauth2/token

{
  "iss": "urn:com:networknt:oauth2:v1",
  "aud": "urn:com.networknt",
  "exp": 1528225473,
  "jti": "9BFwuW1xx7E6u9jdeC8xug",
  "iat": 1528224873,
  "nbf": 1528224753,
  "version": "1.0",
  "user_id": "admin",
  "user_type": "Employee",
  "client_id": "7a3f5f5c-61c8-4b67-8e6d-d95e717dc07d",
  "scope": [
     **"t.r",
     "t.w"**
  ],
  "transit": "12345"
}

**Comment by chenyan71** [comment]
fixed the issue by updating the IMap cache, the hazelcast will store the cache to client table to update the client scope
