### ISSUE TITLE
Create a none-multicast option for Hazelcast 

### ISSUE THREAD

**Issue by auahmed** [networknt/light-oauth2#125]
If multicast is not the prefered way of discovery for the environment, then there should be a configurable way for Hazelcast for full TCP/IP cluster

**Comment by stevehu** [comment]
Add support for externalized hazelcast.xml in config folder so that you can change the default configuration with other discovery methods. Also, to support Kubernetes cluster hazelcast-kubernetes plugin has been included in the classpath.
