### ISSUE TITLE
oauth2-code health check path does not have service ID

### ISSUE THREAD

**Issue by dz-1** [networknt/light-oauth2#160]
The health check path of oauth2-code does not contain service id. As a result, the service cannot work properly with consul.

**Comment by stevehu** [comment]
The fix doesn't work as the endpoint is not in the openapi.yml specification. The following error shows up when issuing `curl -k https://localhost:6881/health/com.networknt.oauth2-code-1.0.0`

```
{"statusCode":404,"code":"ERR10007","message":"INVALID_REQUEST_PATH","description":"Request path /health/com.networknt.oauth2-code-1.0.0 cannot be found in the spec.","severity":"ERROR"}
```

I cannot remember why this code service is not converted to the handler.yml for path config. Need to look into it again.

**Comment by dz-1** [comment]
The handlers in services.yml need to be cleaned up.

**Comment by stevehu** [comment]
I have added an endpoint to the openapi.yml and testing now. Do you mean that some of the middleware handlers need to be removed for code service?

```
  /health/{serviceId}:
    get:
      description: Return OK with response code 200 to indicate healthy
      operationId: getHealth
      parameters:
        - name: serviceId
          description: 'serviceId for the code service'
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Operation

```

**Comment by dz-1** [comment]
I think all the middleware handlers in `service.yml` need to be removed.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [oauth2-code health check path does not have service ID](https://trello.com/c/8YtSTG7i/188-oauth2-code-health-check-path-does-not-have-service-id)
