### ISSUE TITLE
Build error with dependency ojdbc6

### ISSUE THREAD

**Issue by Anaxilaus** [networknt/light-oauth2#212]
I tried building head at both master and 2.0.6, with both openjdk11 and openjdk12(using jenv).
Build fails as it says `ojdbc6-*.jar;zip END header not found`.

I'm on macOS. To reproduce the issue, below is the result of `mvn clean install`:
<details><summary>Output</summary>
<pre>
➜  light-oauth2 git:(master) mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 12 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 12 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Parent POM                                                         [pom]
[INFO] oauth2-cache                                                       [jar]
[INFO] oauth2-authhub                                                     [jar]
[INFO] oauth2-code                                                        [jar]
[INFO] oauth2-token                                                       [jar]
[INFO] oauth2-client                                                      [jar]
[INFO] oauth2-service                                                     [jar]
[INFO] oauth2-user                                                        [jar]
[INFO] oauth2-key                                                         [jar]
[INFO] oauth2-refresh-token                                               [jar]
[INFO] oauth2-authorize                                                   [jar]
[INFO] oauth2-provider                                                    [jar]
[INFO]
[INFO] ---------------------< com.networknt:light-oauth2 >---------------------
[INFO] Building Parent POM 2.0.6                                         [1/12]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ light-oauth2 ---
[INFO] Deleting /Users/Anaxilaus/networknt/light-oauth2/target
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.4.201502262128:prepare-agent (pre-unit-test) @ light-oauth2 ---
[INFO] surefireArgLine set to -javaagent:/Users/Anaxilaus/.m2/repository/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128-runtime.jar=destfile=/Users/Anaxilaus/networknt/light-oauth2/target/jacoco.exec
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.4.201502262128:report (post-unit-test) @ light-oauth2 ---
[INFO] Skipping JaCoCo execution due to missing execution data file:/Users/Anaxilaus/networknt/light-oauth2/target/jacoco.exec
[INFO]
[INFO] --- javadoc-packagelist-maven-plugin:1.0.0:gen-package-list (default) @ light-oauth2 ---
[INFO]
[INFO] >>> maven-source-plugin:3.0.1:jar (attach-sources) > generate-sources @ light-oauth2 >>>
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.4.201502262128:prepare-agent (pre-unit-test) @ light-oauth2 ---
[INFO] surefireArgLine set to -javaagent:/Users/Anaxilaus/.m2/repository/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128-runtime.jar=destfile=/Users/Anaxilaus/networknt/light-oauth2/target/jacoco.exec
[INFO]
[INFO] <<< maven-source-plugin:3.0.1:jar (attach-sources) < generate-sources @ light-oauth2 <<<
[INFO]
[INFO]
[INFO] --- maven-source-plugin:3.0.1:jar (attach-sources) @ light-oauth2 ---
[INFO]
[INFO] --- maven-javadoc-plugin:3.1.0:jar (attach-javadocs) @ light-oauth2 ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ light-oauth2 ---
[INFO] Installing /Users/Anaxilaus/networknt/light-oauth2/pom.xml to /Users/Anaxilaus/.m2/repository/com/networknt/light-oauth2/2.0.6/light-oauth2-2.0.6.pom
[INFO]
[INFO] ---------------------< com.networknt:oauth2-cache >---------------------
[INFO] Building oauth2-cache 2.0.6                                       [2/12]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.oracle:ojdbc6:jar:11.2.0.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ oauth2-cache ---
[INFO] Deleting /Users/Anaxilaus/networknt/light-oauth2/cache/target
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.4.201502262128:prepare-agent (pre-unit-test) @ oauth2-cache ---
[INFO] surefireArgLine set to -javaagent:/Users/Anaxilaus/.m2/repository/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128-runtime.jar=destfile=/Users/Anaxilaus/networknt/light-oauth2/cache/target/jacoco.exec
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ oauth2-cache ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ oauth2-cache ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 30 source files to /Users/Anaxilaus/networknt/light-oauth2/cache/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] error reading /Users/Anaxilaus/.m2/repository/com/oracle/ojdbc6/11.2.0.3/ojdbc6-11.2.0.3.jar; zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ClientComparator.java:[1,1] cannot access com.networknt.oauth.cache.model
  zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/CacheStartupHookProvider.java:[1,1] cannot access com.networknt.oauth.cache
  zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ClientDataSerializableFactory.java:[9,8] cannot access com.networknt.oauth
  zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ClientDataSerializableFactory.java:[9,55] cannot find symbol
  symbol: class DataSerializableFactory
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ClientDataSerializableFactory.java:[15,12] cannot find symbol
  symbol:   class IdentifiedDataSerializable
  location: class com.networknt.oauth.cache.model.ClientDataSerializableFactory
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[7,8] cannot access com.networknt
  zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[7,51] cannot find symbol
  symbol: class Comparator
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[7,74] cannot find symbol
  symbol: class Serializable
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[7,62] cannot access Map
  zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[9,27] package Map does not exist
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[9,41] package Map does not exist
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[19,8] cannot access com
  zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[19,41] cannot find symbol
  symbol: class MapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[19,58] cannot find symbol
  symbol: class Service
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[20,26] cannot find symbol
  symbol:   class Logger
  location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[21,26] cannot find symbol
  symbol:   class DataSource
  location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[40,48] cannot find symbol
  symbol:   class Service
  location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[71,39] cannot find symbol
  symbol:   class Map
  location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[71,51] cannot find symbol
  symbol:   class Service
  location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[76,40] cannot find symbol
  symbol:   class Collection
  location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[80,25] cannot find symbol
  symbol:   class Service
  location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[103,54] cannot find symbol
  symbol:   class Collection
  location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[103,25] cannot find symbol
  symbol:   class Map
  location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[103,37] cannot find symbol
  symbol:   class Service
  location: class com.networknt.oauth.cache.ServiceMapStore
[INFO] 25 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Parent POM 2.0.6:
[INFO]
[INFO] Parent POM ......................................... SUCCESS [  1.793 s]
[INFO] oauth2-cache ....................................... FAILURE [  1.379 s]
[INFO] oauth2-authhub ..................................... SKIPPED
[INFO] oauth2-code ........................................ SKIPPED
[INFO] oauth2-token ....................................... SKIPPED
[INFO] oauth2-client ...................................... SKIPPED
[INFO] oauth2-service ..................................... SKIPPED
[INFO] oauth2-user ........................................ SKIPPED
[INFO] oauth2-key ......................................... SKIPPED
[INFO] oauth2-refresh-token ............................... SKIPPED
[INFO] oauth2-authorize ................................... SKIPPED
[INFO] oauth2-provider .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.201 s
[INFO] Finished at: 2019-10-25T22:01:17+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project oauth2-cache: Compilation failure: Compilation failure:
[ERROR] error reading /Users/Anaxilaus/.m2/repository/com/oracle/ojdbc6/11.2.0.3/ojdbc6-11.2.0.3.jar; zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ClientComparator.java:[1,1] cannot access com.networknt.oauth.cache.model
[ERROR]   zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/CacheStartupHookProvider.java:[1,1] cannot access com.networknt.oauth.cache
[ERROR]   zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ClientDataSerializableFactory.java:[9,8] cannot access com.networknt.oauth
[ERROR]   zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ClientDataSerializableFactory.java:[9,55] cannot find symbol
[ERROR]   symbol: class DataSerializableFactory
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ClientDataSerializableFactory.java:[15,12] cannot find symbol
[ERROR]   symbol:   class IdentifiedDataSerializable
[ERROR]   location: class com.networknt.oauth.cache.model.ClientDataSerializableFactory
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[7,8] cannot access com.networknt
[ERROR]   zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[7,51] cannot find symbol
[ERROR]   symbol: class Comparator
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[7,74] cannot find symbol
[ERROR]   symbol: class Serializable
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[7,62] cannot access Map
[ERROR]   zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[9,27] package Map does not exist
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/model/ServiceEndpointComparator.java:[9,41] package Map does not exist
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[19,8] cannot access com
[ERROR]   zip END header not found
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[19,41] cannot find symbol
[ERROR]   symbol: class MapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[19,58] cannot find symbol
[ERROR]   symbol: class Service
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[20,26] cannot find symbol
[ERROR]   symbol:   class Logger
[ERROR]   location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[21,26] cannot find symbol
[ERROR]   symbol:   class DataSource
[ERROR]   location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[40,48] cannot find symbol
[ERROR]   symbol:   class Service
[ERROR]   location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[71,39] cannot find symbol
[ERROR]   symbol:   class Map
[ERROR]   location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[71,51] cannot find symbol
[ERROR]   symbol:   class Service
[ERROR]   location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[76,40] cannot find symbol
[ERROR]   symbol:   class Collection
[ERROR]   location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[80,25] cannot find symbol
[ERROR]   symbol:   class Service
[ERROR]   location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[103,54] cannot find symbol
[ERROR]   symbol:   class Collection
[ERROR]   location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[103,25] cannot find symbol
[ERROR]   symbol:   class Map
[ERROR]   location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] /Users/Anaxilaus/networknt/light-oauth2/cache/src/main/java/com/networknt/oauth/cache/ServiceMapStore.java:[103,37] cannot find symbol
[ERROR]   symbol:   class Service
[ERROR]   location: class com.networknt.oauth.cache.ServiceMapStore
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :oauth2-cache
</pre>
</details>

**Comment by stevehu** [comment]
@Anaxilaus Thanks a lot for raising it up. A lot of our users are using Oracle internally and that is the only option for them based on the enterprise policy. However, the Oracle JDBC driver cannot be published to Maven central so I found a private repository online to get the driver. It is not reliable and might be down for maintains from time to time. For the master branch, I will remove the Oracle dependency in the next release.

**Comment by stevehu** [comment]
@Anaxilaus I found that the getting-started document has a link to show users how to install the Oracle driver manually. 

https://doc.networknt.com/getting-started/light-oauth2/#build-the-server-from-source-code
