### ISSUE TITLE
CORS issue when calling from a SPA

### ISSUE THREAD

**Issue by gonzalovazquez** [networknt/light-oauth2#23]
Hi Steve,

I have an SPA that calls light-oauth2. 

After trying the latest version of light-oauth2 that supports CORS, I am still getting this error:

`XMLHttpRequest cannot load http://localhost:6883/oauth2/service?page=1. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.`

Could it be because we are specifying the [port number](https://github.com/networknt/light-oauth2/blob/3a1566981a031df18e16cbf0822c30c0dfe074be/service/src/main/resources/config/cors.json#L5)?

Thanks,
Gonzalo

**Comment by stevehu** [comment]
Yes. It is due to the port number. Thanks for pointing it out. Now I have set the allowed origin to "http://localhost:8080"
