### ISSUE TITLE
docker-compose.exe -f docker-compose-mysql.yml up  failed

### ISSUE THREAD

**Issue by brianincd** [networknt/light-oauth2#231]
Hi,
When I try to execute

docker-compose.exe -f docker-compose-mysql.yml up
or
docker build -f Dockerfile .

it always show this：

ADD failed: stat /var/lib/docker/tmp/docker-builder215098260/target/oauth2-code.jar: no such file or directory
--

docker engine:18.06.1-ce
compose:1.22.0

**Comment by brianincd** [comment]
I passed  'mvn clean install'，and there is jar file in the path "/target/oauth2-key.jar"

**Comment by stevehu** [comment]
If you are not planning to change the light-oauth2, please use the https://github.com/networknt/light-docker/blob/master/docker-compose-oauth2-mysql.yml

For developers of the light-oauth2, you need to build the jar locally and then call the docker-compse

**Comment by brianincd** [comment]
> If you are not planning to change the light-oauth2, please use the https://github.com/networknt/light-docker/blob/master/docker-compose-oauth2-mysql.yml
> 
> For developers of the light-oauth2, you need to build the jar locally and then call the docker-compse

Got it ,thx
