### ISSUE TITLE
clientSecret hash is leaked on GET request

### ISSUE THREAD

**Issue by smerschjohann** [networknt/light-oauth2#27]
Currently the hash of the clientsecret is leaked if details to a clientId are requested.

It would be better to nullify this value in `Oauth2ClientClientIdGetHandler.java` before returning it.

**Comment by stevehu** [comment]
Thanks for pointing out this issue. I have revisited all get endpoints and using client copy to replace the object returned from in-memory data grid. When we are doing this, there is no way for client owner to get secret if they forget it. We need to give another interface to reset secret or query secret somehow. Must login as client owner to do that. Currently, the security is not enabled by default on these microservices but will soon be enabled and only portal will be able to access these registration endpoints.
