### ISSUE TITLE
Inject server/info and /health into swagger for oauth2 services.

### ISSUE THREAD

**Issue by stevehu** [networknt/light-oauth2#36]

**Comment by j-kinyanjui** [comment]
I have this system currently in testing and rolled out in DC/OS. When jwt verification is set as true for certain micro-services (specifically, client and user). While accessing the /health endpoint, the service responds with an Unauthorised response. Is there a fix for this? Or does this require a fix by separating the health check route from the other GET paths. I don't think a health check path should require a jwt token
