### ISSUE TITLE
Upgrade docker-compose files and db configurations to 1.5.4

### ISSUE THREAD

**Issue by stevehu** [networknt/light-oauth2#49]
In release 1.5.4, we need separate service.yml config file for each oauth2 services. The change has been done in light-docker and we need to do the same for the local build here in light-oauth2. The light-docker compose file is for developers to start OAuth2 providers in his/her local while working on the API projects. The compose file here is for developers who are working on light-oauth2. So the compose is using local build instead of docker hub.

**Comment by DineshAlapati** [comment]
I will be happy to make this update. I will raise a PR once it is done.
