### ISSUE TITLE
support custom claim in json format with client registration

### ISSUE THREAD

**Issue by stevehu** [networknt/light-oauth2#75]
Some of our customers want to put custom claims into the generated JWT token so that down stream services will rely on the claims to perform fine-grained authorization. This enhancement is to allow users to add custom_claim as part of the client registration and the token service will check if custom_claim is empty to add it the to JWT token generated.

**Comment by Rajith90** [comment]
I have registered a client with following command.

`curl -k -H "Content-Type: application/json" -X POST -d '{"clientType":"public","clientProfile":"mobile","clientName":"AccountViewer","clientDesc":"Retail Online Banking Account Viewer","scope":"act.r act.w","redirectUri": "http://localhost:8080/authorization","ownerId":"admin", "customClaim":"{\"sub\":\"admin\"}"}' https://localhost:6884/oauth2/client`

In the response I get custom claims as below

`"customClaim":"{\\\"sub\\\":\\\"admin\\\"}`

But when I Invoke token endpoint with client credential grant for the above client id and secret I get the following error.

`com.fasterxml.jackson.core.JsonParseException: Unexpected character ('\' (code 92)): was expecting double-quote to start field name
oauth2-token_1          |  at [Source: (String)"{\"sub\":\"admin\"}"; line: 1, column: 3]
oauth2-token_1          | 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
oauth2-token_1          | 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
oauth2-token_1          | 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591)
oauth2-token_1          | 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1767)
oauth2-token_1          | 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:917)
oauth2-token_1          | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:500)
oauth2-token_1          | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
oauth2-token_1          | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
oauth2-token_1          | 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
oauth2-token_1          | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3023)
oauth2-token_1          | 	at com.networknt.oauth.token.handler.Oauth2TokenPostHandler.handleClientCredentials(Oauth2TokenPostHandler.java:160)
oauth2-token_1          | 	at com.networknt.oauth.token.handler.Oauth2TokenPostHandler.handleRequest(Oauth2TokenPostHandler.java:116)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.openapi.ValidatorHandler.handleRequest(ValidatorHandler.java:88)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.sanitizer.SanitizerHandler.handleRequest(SanitizerHandler.java:104)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.audit.AuditHandler.next(AuditHandler.java:157)
oauth2-token_1          | 	at com.networknt.audit.AuditHandler.handleRequest(AuditHandler.java:146)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.body.BodyHandler.handleRequest(BodyHandler.java:116)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.openapi.OpenApiHandler.handleRequest(OpenApiHandler.java:88)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.correlation.CorrelationHandler.handleRequest(CorrelationHandler.java:73)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.traceability.TraceabilityHandler.handleRequest(TraceabilityHandler.java:66)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:73)
oauth2-token_1          | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
oauth2-token_1          | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
oauth2-token_1          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oauth2-token_1          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oauth2-token_1          | 	at java.lang.Thread.run(Thread.java:748)
oauth2-token_1          | 10:12:33.178 [XNIO-1 task-42]  o8qvYnbBQw6lvUDj5g9H4Q ERROR c.n.o.t.h.Oauth2TokenPostHandler handleRequest - ApiException
oauth2-token_1          | com.networknt.exception.ApiException: {"statusCode":400,"code":"ERR10014","message":"GENERIC_EXCEPTION","description":"Generic Exception Unexpected character ('\' (code 92)): was expecting double-quote to start field name
oauth2-token_1          |  at [Source: (String)"{\"sub\":\"admin\"}"; line: 1, column: 3].","severity":"ERROR"}
oauth2-token_1          | 	at com.networknt.oauth.token.handler.Oauth2TokenPostHandler.handleClientCredentials(Oauth2TokenPostHandler.java:165)
oauth2-token_1          | 	at com.networknt.oauth.token.handler.Oauth2TokenPostHandler.handleRequest(Oauth2TokenPostHandler.java:116)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.openapi.ValidatorHandler.handleRequest(ValidatorHandler.java:88)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.sanitizer.SanitizerHandler.handleRequest(SanitizerHandler.java:104)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.audit.AuditHandler.next(AuditHandler.java:157)
oauth2-token_1          | 	at com.networknt.audit.AuditHandler.handleRequest(AuditHandler.java:146)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.body.BodyHandler.handleRequest(BodyHandler.java:116)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.openapi.OpenApiHandler.handleRequest(OpenApiHandler.java:88)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.correlation.CorrelationHandler.handleRequest(CorrelationHandler.java:73)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.traceability.TraceabilityHandler.handleRequest(TraceabilityHandler.java:66)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:207)
oauth2-token_1          | 	at com.networknt.handler.Handler.next(Handler.java:228)
oauth2-token_1          | 	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:73)
oauth2-token_1          | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
oauth2-token_1          | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
oauth2-token_1          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oauth2-token_1          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oauth2-token_1          | 	at java.lang.Thread.run(Thread.java:748)
`

How Can get tokens with custom JWT claims

**Comment by stevehu** [comment]
I haven't figure out how to use curl to populate custom claims due to quote issue. You can update the database directly with you pipeline for client registry or use the light-portal view to registry the client.
