### ISSUE TITLE
add ms sql server support

### ISSUE THREAD

**Issue by stevehu** [networknt/light-oauth2#84]
One of our customers is asking if we can support MS SQLServer for the database. I think it should be easy as long as we have access to MS SQLServer instance to test.

**Comment by chenyan71** [comment]
Add new docker-compose file for SQL-server support:
docker-compose-sqlserver.yml

Run docker-compose on the light-oauth2 root folder:
docker-compose -f docker-compose-sqlserver.yml up

We use MS SQLServer linux image which works on both linux and Mac
--microsoft/mssql-server-linux:2017-latest

JDBC connection based on dependency:
            <dependency>
                <groupId>com.microsoft.sqlserver</groupId>
                <artifactId>mssql-jdbc</artifactId>
                <version>6.5.1.jre8-preview</version>
            </dependency>

**Comment by stevehu** [comment]
@chenyan71 Thanks a lot.
